In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
A = np.random.randn(10)

In [7]:
A

array([-0.38004389, -1.17087494, -0.52345337, -1.56084532,  0.40657463,
       -3.12299368, -1.26033294, -1.68144659,  0.8691242 ,  0.70396048])

In [8]:
B = np.random.randn(10)

In [9]:
B

array([ 0.58646394,  1.1888018 , -1.78202419,  0.1591856 ,  0.47340738,
        0.5588626 ,  0.91338136, -0.485734  , -1.47806493, -2.49940706])

In [10]:
np.add(A,B)

array([ 0.20642005,  0.01792686, -2.30547756, -1.40165972,  0.87998201,
       -2.56413108, -0.34695158, -2.16718059, -0.60894073, -1.79544657])

In [11]:
np.maximum(A,B)

array([ 0.58646394,  1.1888018 , -0.52345337,  0.1591856 ,  0.47340738,
        0.5588626 ,  0.91338136, -0.485734  ,  0.8691242 ,  0.70396048])